CREATE TABLE users
(
    id          CHARACTER VARYING(60) PRIMARY KEY,
    login       CHARACTER VARYING(30) NOT NULL UNIQUE,
    first_name   CHARACTER VARYING(30) NOT NULL,
    surname     CHARACTER VARYING(30) NOT NULL,
    email       CHARACTER VARYING(30) NOT NULL,
    phone_number CHARACTER VARYING(30) NOT NULL,
    country     CHARACTER VARYING(30) NOT NULL
);